//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;


namespace MVCInvoiceMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public int ProviderID { get; set; }

        [DisplayName("Company Name")]
        public string Name { get; set; }
        public string CompanyNumber { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string City { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }

        [DisplayName("Company Logo")]
        public string CompanyLogo { get; set; }
    }
}
